export const MOVIES_MOCK = [
  {
    id: "peaky-blinders",
    title: "Peaky Blinders",
    trailerId: "oVzVdvGIC7U",
    releaseYear: 2013,
    ageLimit: "16+",
    rating: "8.8/10",
    duration: "1hr 25min",
    mainCharacterName: "Tommy Shelby",
    description:
      "Tommy Shelby, a dangerous man, leads the Peaky Blinders, a gang based in Birmingham. Soon, Chester Campbell, an inspector, decides to nab him and put an end to the criminal activities.",
    assets: {
      background: "/peaky-blinders/main-bg.png",
      videoCover: "/peaky-blinders/video-cover.png",
      mainCharacter: "/peaky-blinders/main-character.png",
      logo: "/peaky-blinders/film-logo.png",
    },
    seasons: [
      { number: 1, link: "/watch/peaky-blinders/s1" },
      { number: 2, link: "/watch/peaky-blinders/s2" },
      { number: 3, link: "/watch/peaky-blinders/s3" },
      { number: 4, link: "/watch/peaky-blinders/s4" },
      { number: 5, link: "/watch/peaky-blinders/s5" },
      { number: 6, link: "/watch/peaky-blinders/s6" },
    ],
  },
  {
    id: "bloodhounds",
    title: "Bloodhounds",
    trailerId: "eyiR8pO50JE",
    releaseYear: 2023,
    ageLimit: "18+",
    rating: "8.1/10",
    duration: "1hr 0min",
    mainCharacterName: "Kim Gun-woo",
    description:
      "Two young boxers band together with a benevolent moneylender to take down a ruthless loan shark who preys on the financially desperate.",
    assets: {
      background: "/bloodhounds/main-bg.png",
      videoCover: "/bloodhounds/video-cover.png",
      mainCharacter: "/bloodhounds/main-character.png",
      logo: "/bloodhounds/film-logo.png",
    },
    seasons: [{ number: 1, link: "/watch/bloodhounds/s1" }],
  },
  {
    id: "dont-look-up",
    title: "Don't Look Up",
    trailerId: "RbIxYm3mKzI",
    releaseYear: 2021,
    ageLimit: "16+",
    rating: "7.2/10",
    duration: "2hr 18min",
    mainCharacterName: "Randall Mindy",
    description:
      "Two low-level astronomers must go on a giant media tour to warn mankind of an approaching comet that will destroy planet Earth.",
    assets: {
      background: "/dont-look-up/main-bg.png",
      videoCover: "/dont-look-up/video-cover.png",
      mainCharacter: "/dont-look-up/main-character.png",
      logo: "/dont-look-up/film-logo.png",
    },
    seasons: [], // Это фильм
  },
  {
    id: "narcos",
    title: "Narcos",
    trailerId: "xl8zdCY-abw",
    releaseYear: 2015,
    ageLimit: "18+",
    rating: "8.8/10",
    duration: "49min",
    mainCharacterName: "Pablo Escobar",
    description:
      "A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar, as well as many other drug kingpins who plagued the country through the years.",
    assets: {
      background: "/narcos/main-bg.png",
      videoCover: "/narcos/video-cover.png",
      mainCharacter: "/narcos/main-character.png",
      logo: "/narcos/film-logo.png",
    },
    seasons: [
      { number: 1, link: "/watch/narcos/s1" },
      { number: 2, link: "/watch/narcos/s2" },
      { number: 3, link: "/watch/narcos/s3" },
    ],
  },
  {
    id: "red-notice",
    title: "Red Notice",
    trailerId: "Pj0wz7zu3Ms",
    releaseYear: 2021,
    ageLimit: "13+",
    rating: "6.3/10",
    duration: "1hr 58min",
    mainCharacterName: "John Hartley",
    description:
      "An Interpol agent successfully tracks down the world's most wanted art thief with help from a rival thief to catch a con artist who's always one step ahead.",
    assets: {
      background: "/red-notice/main-bg.png",
      videoCover: "/red-notice/video-cover.png",
      mainCharacter: "/red-notice/main-character.png",
      logo: "/red-notice/film-logo.png",
    },
    seasons: [], // Это фильм
  },
  {
    id: "squid-game",
    title: "Squid Game",
    trailerId: "oqxAJKy0ii4",
    releaseYear: 2021,
    ageLimit: "18+",
    rating: "8.0/10",
    duration: "55min",
    mainCharacterName: "Seong Gi-hun",
    description:
      "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits with deadly high stakes.",
    assets: {
      background: "/squid-game/main-bg.png",
      videoCover: "/squid-game/video-cover.png",
      mainCharacter: "/squid-game/main-character.png",
      logo: "/squid-game/film-logo.png",
    },
    seasons: [
      { number: 1, link: "/watch/squid-game/s1" },
      { number: 2, link: "/watch/squid-game/s2" },
    ],
  },
  {
    id: "venom",
    title: "Venom",
    trailerId: "u9Mv98Gr5pY",
    releaseYear: 2018,
    ageLimit: "16+",
    rating: "6.6/10",
    duration: "1hr 52min",
    mainCharacterName: "Eddie Brock",
    description:
      "A failed reporter is bonded to an alien entity, one of many symbiotes who have invaded Earth. But the being takes a liking to Earth and decides to protect it.",
    assets: {
      background: "/venom/main-bg.png",
      videoCover: "/venom/video-cover.png",
      mainCharacter: "/venom/main-character.png",
      logo: "/venom/film-logo.png",
    },
    seasons: [], // Это фильм
  },
  {
    id: "wednesday",
    title: "Wednesday",
    trailerId: "Di310WS8zLk",
    releaseYear: 2022,
    ageLimit: "16+",
    rating: "8.1/10",
    duration: "45min",
    mainCharacterName: "Wednesday Addams",
    description:
      "While attending Nevermore Academy, Wednesday Addams attempts to master her emerging psychic ability, thwart a killing spree and solve the mystery that embroiled her parents 25 years ago.",
    assets: {
      background: "/wednesday/main-bg.png",
      videoCover: "/wednesday/video-cover.png",
      mainCharacter: "/wednesday/main-character.png",
      logo: "/wednesday/film-logo.png",
    },
    seasons: [{ number: 1, link: "/watch/wednesday/s1" }],
  },
  {
    id: "the-eternaut",
    title: "The Eternaut",
    trailerId: "TqT4fDQQqCc",
    releaseYear: 2025,
    ageLimit: "18+",
    rating: "TBD",
    duration: "1hr",
    mainCharacterName: "Juan Salvo",
    description:
      "After a deadly snowfall kills millions, Juan Salvo and a group of survivors fight against an alien threat controlled by an invisible force.",
    assets: {
      background: "/the-eternaut/main-bg.png",
      videoCover: "/the-eternaut/video-cover.png",
      mainCharacter: "/the-eternaut/main-character.png",
      logo: "/the-eternaut/film-logo.png",
    },
    seasons: [{ number: 1, link: "/watch/the-eternaut/s1" }],
  },
  {
    id: "mad-max",
    title: "Mad Max: Fury Road",
    trailerId: "hEJnMQG9ev8",
    releaseYear: 2015,
    ageLimit: "18+",
    rating: "8.1/10",
    duration: "2hr 0min",
    mainCharacterName: "Max Rockatansky",
    description:
      "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.",
    assets: {
      background: "/mad-max/main-bg.png",
      videoCover: "/mad-max/video-cover.png",
      mainCharacter: "/mad-max/main-character.png",
      logo: "/mad-max/film-logo.png",
    },
    seasons: [], // Это фильм
  },
]
